language: rust
script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo test --verbose --features thread-local
  - cargo doc
after_success: |
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  echo '<meta http-equiv=refresh content=0;url=tls/index.html>' > target/doc/index.html &&
  sudo pip install ghp-import &&
  ghp-import -n target/doc &&
  git push -fq https://${TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
env:
  global:
    secure: VVa6wc+p7F+Trdy0vmiqVMaHmrcq+2JcNE2S8f9b57p2wV4jdXQd47UH34hJ4+Oou2ehbRJwZ+kmdr6dyGC76PwMzAFoVm0kWmeJtGI5UqeckUboSc6sXkMzmwKM+65jKuYt83W3KwHyqtfQ7P6JiNjWZY6j62tVG9t9xMJQPpg=
notifications:
  email:
    on_success: never
